services:
  antmedia-pos:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antmedia-pos
    ports:
      - "5081:5080"     # HTTP port
      # - "5443:5443"     # HTTPS port  
      # - "1935:1935"     # RTMP port
      # - "5554:5554"     # WebRTC port
      - "3000:3000"     # Frontend port
    volumes:
      - antmedia_data:/usr/local/antmedia
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    restart: unless-stopped
    
volumes:
  antmedia_data:
    driver: local